# Generated by Django 2.2.28 on 2022-05-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LIVES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['person_name'],
            },
        ),
        migrations.CreateModel(
            name='WORKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('salary', models.FloatField()),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LIVES')),
            ],
        ),
    ]
