# Generated by Django 2.2.28 on 2022-05-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lives',
            options={},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ['person_name']},
        ),
    ]
