# Generated by Django 2.2.28 on 2022-05-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220501_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LIVES'),
        ),
    ]
